spring.datasource.url=jdbc:postgresql://dpg-d6tvsdaa214c73crarpg-a.oregon-postgres.render.com/binova
spring.datasourse.username=binova_user
spring,datasource.password=iFl6DR8XhJ1PvgRlR4Cc9fG8koX2H4Q2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-
name=org.postgresql.driver
